### PR TITLE
Relicense to LGPL

### PR DESCRIPTION
**Pull request by Earthcomputer**
Relicense this plugin from GPL-3.0 to LGPL-3.0, so that it can be ported to a mod and developed further.

All contributors who made substantial changes need to agree to the license change with the following wording. If you are a contributor listed below, please respond by commenting on this PR.

> I `github user` listed above as `email address` consent to the relicensing of my contributions to the Descent Into Darkness project under the license as stated in LICENSE.

- [x] Earthcomputer (burtonjae@hotmail.co.uk)
- [x] samnrad (samnrad@users.noreply.github.com)
- [x] Sharpcastle33 (Sharpcastle33@users.noreply.github.com)

### CODE REVIEW

**Comment by Earthcomputer** [comment]
I Earthcomputer listed above as burtonjae@hotmail.co.uk consent to the relicensing of my contributions to the Descent Into Darkness project under the license as stated in LICENSE.

**Comment by Sharpcastle33** [comment]
I'm not particularly against LGPL, but I'm curious what requires a license change? You should be able to modify to your hearts content with GPL3 provided you release the source code

**Comment by Earthcomputer** [comment]
> I'm not particularly against LGPL, but I'm curious what requires a license change

You can make GPL plugins, but only LGPL mods. This is because a plugin doesn't directly reference Minecraft code.

**Comment by Sharpcastle33** [comment]
I Sharpcastle33 listed above as Sharpcastle33@users.noreply.github.com consent to the relicensing of my contributions to the Descent Into Darkness project under the license as stated in LICENSE.

**Comment by samnrad** [comment]
I Samnrad listed above as [samnrad@users.noreply.github.com](mailto:samnrad@users.noreply.github.com) consent to the relicensing of my contributions to the Descent Into Darkness project under the license as stated in LICENSE.

**Comment by Earthcomputer** [comment]
Thanks everyone!

**Pull request merged**
